// packages/vue/src/InlineSurface.vue
<script setup lang="ts" generic="TExtra extends object = object">
import {
    SelectBoxSnapshotView,
    type SelectBoxController,
    type SelectBoxSnapshot,
    type SelectionValue,
    type SelectOption,
} from "@select-box/core";
import FormMirror from "./FormMirror.vue";
import { computed, useTemplateRef } from "vue";

const props = defineProps<{
    state: SelectBoxSnapshot<TExtra, SelectionValue>;
    controller: SelectBoxController<TExtra, SelectionValue>;
    name: string | undefined;
    required: boolean | undefined;
}>();

const rootRef = useTemplateRef<HTMLDivElement>("rootEl");

defineExpose({ root: rootRef });

const isMulti = computed(() => props.state.mode === "multi");
const view = computed(
    () => new SelectBoxSnapshotView<TExtra, SelectionValue>(props.state),
);

function commitInlineChip(option: SelectOption<TExtra>): void {
    if (option.disabled) return;
    props.controller.commitOption(option);
}

function inlineChipClass(isSelected: boolean, disabled: boolean | undefined): string {
    return [
        "select-box-chip",
        "select-box-chip-selectable",
        isSelected ? "select-box-chip-selected" : null,
        disabled ? "select-box-chip-disabled" : null,
    ]
        .filter((value): value is string => value !== null)
        .join(" ");
}
</script>

<template>
    <div
        ref="rootEl"
        :class="['select-box', isMulti ? 'select-box-multi' : null].filter(Boolean).join(' ')"
        data-select-root
        :data-select-mode="state.mode"
    >
        <FormMirror :state="state" :controller="controller" :name="name" :required="required" />
        <!-- The surface is a child of the root in every wrapper, so the root
             never doubles as a listbox and one selector addresses either. -->
        <div
            class="select-box-inline"
            role="listbox"
            :aria-multiselectable="isMulti ? true : undefined"
            data-select-surface="inline"
        >
        <template v-for="group in state.filteredGroups" :key="group.key">
            <div
                v-if="group.label"
                class="select-box-group-label"
                data-select-group-label
            >{{ group.label }}</div>
            <div class="select-box-tags" data-select-tags>
                <button
                    v-for="option in group.options"
                    :key="option.value"
                    type="button"
                    role="option"
                    :aria-selected="view.isSelected(option.value)"
                    :aria-pressed="view.isSelected(option.value)"
                    :disabled="option.disabled === true || state.disabled || state.readOnly"
                    :class="inlineChipClass(view.isSelected(option.value), option.disabled)"
                    data-select-chip
                    data-select-option
                    :data-select-selected="view.isSelected(option.value) ? '' : undefined"
                    @click="commitInlineChip(option)"
                >{{ option.label }}</button>
            </div>
        </template>
        </div>
    </div>
</template>

// packages/react/src/InlineSurface.tsx
import {
    SelectBoxSnapshotView,
    type SelectBoxController,
    type SelectBoxSnapshot,
    type SelectionValue,
    type SelectOption,
} from "@select-box/core";
import { Fragment, useMemo, type JSX, type Ref } from "react";

import { FormMirror } from "./FormMirror.js";

export interface InlineSurfaceProps<TExtra extends object> {
    readonly state: SelectBoxSnapshot<TExtra, SelectionValue>;
    readonly controller: SelectBoxController<TExtra, SelectionValue>;
    readonly rootRef: Ref<HTMLDivElement> | undefined;
    readonly name: string | undefined;
    readonly required: boolean | undefined;
    readonly className: string | undefined;
    readonly ariaLabel: string | undefined;
    readonly ariaLabelledby: string | undefined;
}

/**
 * Inline-chip surface: every option is rendered as a toggleable chip; clicking
 * a chip commits it through the active selection driver (single replaces,
 * multi toggles). No popover, no trigger input, no search — group headers are
 * still rendered above their chips when the option set is grouped.
 */
export function InlineSurface<TExtra extends object>({
    state,
    controller,
    rootRef,
    name,
    required,
    className,
    ariaLabel,
    ariaLabelledby,
}: InlineSurfaceProps<TExtra>): JSX.Element {
    const isMulti = state.mode === "multi";
    const view = useMemo(
        () => new SelectBoxSnapshotView<TExtra, SelectionValue>(state),
        [state],
    );

    const rootClassName = [
        "select-box",
        isMulti ? "select-box-multi" : null,
        className,
    ]
        .filter(Boolean)
        .join(" ");

    function handleChipClick(option: SelectOption<TExtra>): void {
        if (option.disabled) return;
        controller.commitOption(option);
    }

    return (
        <div
            ref={rootRef}
            className={rootClassName}
            data-select-root
            data-select-mode={state.mode}
        >
            <FormMirror state={state} controller={controller} name={name} required={required} />
            {/* The surface is a child of the root in every wrapper, so the root
                never doubles as a listbox and one selector addresses either. */}
            <div
                className="select-box-inline"
                role="listbox"
                aria-multiselectable={isMulti ? true : undefined}
                aria-label={ariaLabel}
                aria-labelledby={ariaLabelledby}
                data-select-surface="inline"
            >
            {state.filteredGroups.map((group) => (
                <Fragment key={group.key}>
                    {group.label ? (
                        <div
                            className="select-box-group-label"
                            data-select-group-label
                        >
                            {group.label}
                        </div>
                    ) : null}
                    <div className="select-box-tags" data-select-tags>
                        {group.options.map((option) => {
                            const isSelected = view.isSelected(option.value);
                            const chipClassName = [
                                "select-box-chip",
                                "select-box-chip-selectable",
                                isSelected ? "select-box-chip-selected" : null,
                                option.disabled ? "select-box-chip-disabled" : null,
                            ]
                                .filter(Boolean)
                                .join(" ");
                            return (
                                <button
                                    key={option.value}
                                    type="button"
                                    role="option"
                                    aria-selected={isSelected}
                                    aria-pressed={isSelected}
                                    disabled={option.disabled === true || state.disabled || state.readOnly}
                                    className={chipClassName}
                                    onClick={() => handleChipClick(option)}
                                    data-select-chip
                                    data-select-option
                                    data-select-selected={isSelected ? "" : undefined}
                                >
                                    {option.label}
                                </button>
                            );
                        })}
                    </div>
                </Fragment>
            ))}
            </div>
        </div>
    );
}
