// packages/react/src/PopoverSurface.tsx
import {
    optionElementId,
    SelectBoxSnapshotView,
    TextHighlighter,
    type SearchMatchRange,
    type SelectBoxKeyDispatcher,
    type SelectBoxController,
    type SelectBoxSnapshot,
    type SelectionValue,
    type SelectOption,
} from "@select-box/core";
import {
    useId,
    useMemo,
    useRef,
    type ChangeEvent,
    type JSX,
    type KeyboardEvent,
    type MouseEvent,
    type Ref,
    type RefObject,
} from "react";

import { useClickOutsideClose } from "./hooks/use-click-outside-close.js";
import { FormMirror } from "./FormMirror.js";
import { useMergedRefs } from "./hooks/use-merged-refs.js";
import { useSelectBoxKeyDispatcher } from "./hooks/use-select-box-key-dispatcher.js";
import { useSelectBoxVirtualizer } from "./hooks/use-select-box-virtualizer.js";

const ESTIMATED_OPTION_HEIGHT = 36;
const ESTIMATED_HEADER_HEIGHT = 28;
const LIST_VIEWPORT_HEIGHT = 240;

export interface PopoverSurfaceProps<TExtra extends object> {
    readonly state: SelectBoxSnapshot<TExtra, SelectionValue>;
    readonly controller: SelectBoxController<TExtra, SelectionValue>;
    readonly rootRef: Ref<HTMLDivElement> | undefined;
    readonly name: string | undefined;
    readonly required: boolean | undefined;
    readonly placeholder: string | undefined;
    readonly className: string | undefined;
    readonly ariaLabel: string | undefined;
    readonly ariaLabelledby: string | undefined;
}

/**
 * Popover-style surface: trigger (single-line input + caret in single mode;
 * chip-line input in multi mode) plus a virtualised dropdown listbox. Owns
 * click-outside-to-close and keyboard navigation — both are popover-only
 * concerns and don't apply to other surfaces.
 */
export function PopoverSurface<TExtra extends object>({
    state,
    controller,
    rootRef: forwardedRootRef,
    name,
    required,
    placeholder,
    className,
    ariaLabel,
    ariaLabelledby,
}: PopoverSurfaceProps<TExtra>): JSX.Element {
    const instanceId = useId();
    // The combobox points at the highlighted row by id, and both sides derive it
    // from the same snapshot rather than passing an index between components.
    const activeDescendant = state.activeOption === null
        ? undefined
        : optionElementId(instanceId, state.activeOption.value);
    const rootRef = useRef<HTMLDivElement>(null);
    const setRootNode = useMergedRefs(rootRef, forwardedRootRef);
    const inputRef = useRef<HTMLInputElement>(null);
    const keyDispatcher = useSelectBoxKeyDispatcher(controller);

    useClickOutsideClose(rootRef, state.open, controller);

    function focusInput(): void {
        inputRef.current?.focus({ preventScroll: true });
    }

    const isMulti = state.mode === "multi";
    const rootClassName = [
        "select-box",
        isMulti ? "select-box-multi" : null,
        className,
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <div
            ref={setRootNode}
            className={rootClassName}
            data-select-root
            data-select-mode={state.mode}
        >
            <FormMirror state={state} controller={controller} name={name} required={required} />
            {isMulti ? (
                <MultiTrigger
                    state={state}
                    controller={controller}
                    inputRef={inputRef}
                    keyDispatcher={keyDispatcher}
                    placeholder={placeholder}
                    ariaLabel={ariaLabel}
                    ariaLabelledby={ariaLabelledby}
                    activeDescendant={activeDescendant}
                    onFocusInput={focusInput}
                />
            ) : (
                <SingleTrigger
                    state={state}
                    controller={controller}
                    inputRef={inputRef}
                    keyDispatcher={keyDispatcher}
                    placeholder={placeholder}
                    ariaLabel={ariaLabel}
                    ariaLabelledby={ariaLabelledby}
                    activeDescendant={activeDescendant}
                />
            )}

            {state.open ? (
                <PopoverListbox
                    state={state}
                    controller={controller}
                    instanceId={instanceId}
                    onAfterCommit={isMulti ? focusInput : undefined}
                />
            ) : null}
        </div>
    );
}

/* ---------------- single trigger ---------------- */

interface SingleTriggerProps<TExtra extends object> {
    readonly state: SelectBoxSnapshot<TExtra, SelectionValue>;
    readonly controller: SelectBoxController<TExtra, SelectionValue>;
    readonly inputRef: RefObject<HTMLInputElement | null>;
    readonly keyDispatcher: SelectBoxKeyDispatcher<TExtra, SelectionValue>;
    readonly placeholder: string | undefined;
    readonly ariaLabel: string | undefined;
    readonly ariaLabelledby: string | undefined;
    readonly activeDescendant: string | undefined;
}

function SingleTrigger<TExtra extends object>({
    state,
    controller,
    inputRef,
    keyDispatcher,
    placeholder,
    ariaLabel,
    ariaLabelledby,
    activeDescendant,
}: SingleTriggerProps<TExtra>): JSX.Element {
    const view = new SelectBoxSnapshotView(state);
    const clearControl = view.clearControl;

    function handleClear(event: MouseEvent<HTMLButtonElement>): void {
        event.stopPropagation();
        controller.clear();
        inputRef.current?.focus({ preventScroll: true });
    }

    function handleInputChange(event: ChangeEvent<HTMLInputElement>): void {
        if (!state.open) controller.open();
        controller.setQuery(event.target.value);
    }

    function handleInputFocus(): void {
        if (!state.open) controller.open();
    }

    function handleInputClick(): void {
        if (!state.open) controller.open();
    }

    function handleCaretMouseDown(event: MouseEvent<HTMLButtonElement>): void {
        event.preventDefault();
    }

    function handleCaretClick(): void {
        if (state.open) {
            controller.close();
        } else {
            controller.open();
            inputRef.current?.focus({ preventScroll: true });
        }
    }

    function handleKeyDown(event: KeyboardEvent<HTMLInputElement>): void {
        if (keyDispatcher.dispatch(event.key) === "handled") event.preventDefault();
    }

    const placeholderText = state.open && state.selectedOption
        ? state.selectedOption.label
        : (placeholder ?? "Select…");

    return (
        <div className="select-box-trigger" data-select-trigger>
            <input
                ref={inputRef}
                type="text"
                className="select-box-input"
                role="combobox"
                aria-haspopup="listbox"
                aria-expanded={state.open}
                aria-autocomplete="list"
                aria-label={ariaLabel}
                aria-labelledby={ariaLabelledby}
                aria-activedescendant={activeDescendant}
                placeholder={placeholderText}
                value={view.triggerInputValue}
                onChange={handleInputChange}
                onFocus={handleInputFocus}
                onClick={handleInputClick}
                onKeyDown={handleKeyDown}
                disabled={state.disabled}
                readOnly={state.readOnly}
                aria-readonly={state.readOnly || undefined}
                data-select-input
            />
            <button
                type="button"
                className="select-box-caret"
                data-select-caret
                onMouseDown={handleCaretMouseDown}
                onClick={handleCaretClick}
                tabIndex={-1}
                aria-hidden
            >
                ▾
            </button>
            {clearControl.visible && (
                <button
                    type="button"
                    className="select-box-clear"
                    aria-label={clearControl.ariaLabel}
                    tabIndex={-1}
                    onMouseDown={(event) => event.stopPropagation()}
                    onClick={handleClear}
                    data-select-clear
                >
                    {clearControl.label}
                </button>
            )}
        </div>
    );
}

/* ---------------- multi trigger ---------------- */

interface MultiTriggerProps<TExtra extends object> {
    readonly state: SelectBoxSnapshot<TExtra, SelectionValue>;
    readonly controller: SelectBoxController<TExtra, SelectionValue>;
    readonly inputRef: RefObject<HTMLInputElement | null>;
    readonly keyDispatcher: SelectBoxKeyDispatcher<TExtra, SelectionValue>;
    readonly placeholder: string | undefined;
    readonly ariaLabel: string | undefined;
    readonly ariaLabelledby: string | undefined;
    readonly activeDescendant: string | undefined;
    readonly onFocusInput: () => void;
}

function MultiTrigger<TExtra extends object>({
    state,
    controller,
    inputRef,
    keyDispatcher,
    placeholder,
    ariaLabel,
    ariaLabelledby,
    activeDescendant,
    onFocusInput,
}: MultiTriggerProps<TExtra>): JSX.Element {
    function handleControlMouseDown(event: MouseEvent<HTMLDivElement>): void {
        if (event.target !== inputRef.current) event.preventDefault();
        if (!state.open) controller.open();
        onFocusInput();
    }

    function handleInputChange(event: ChangeEvent<HTMLInputElement>): void {
        if (!state.open) controller.open();
        controller.setQuery(event.target.value);
    }

    function handleInputFocus(): void {
        if (!state.open) controller.open();
    }

    function handleKeyDown(event: KeyboardEvent<HTMLInputElement>): void {
        if (keyDispatcher.dispatch(event.key) === "handled") event.preventDefault();
    }

    function handleChipRemove(
        option: SelectOption<TExtra>,
        event: MouseEvent<HTMLButtonElement>,
    ): void {
        event.stopPropagation();
        controller.commitOption(option);
        onFocusInput();
    }

    function handleClearAll(event: MouseEvent<HTMLButtonElement>): void {
        event.stopPropagation();
        controller.clear();
        onFocusInput();
    }

    const hasSelection = state.selectedOptions.length > 0;
    const placeholderText = hasSelection ? "" : (placeholder ?? "Select…");
    const view = new SelectBoxSnapshotView<TExtra, SelectionValue>(state);
    const clearControl = view.clearControl;
    const removeControl = view.removeControl;

    return (
        <div
            className="select-box-trigger"
            data-select-trigger
            role="combobox"
            aria-expanded={state.open}
            aria-haspopup="listbox"
            aria-label={ariaLabel}
            aria-labelledby={ariaLabelledby}
            aria-activedescendant={activeDescendant}
            onMouseDown={handleControlMouseDown}
        >
            <div className="select-box-tags" data-select-tags>
                {state.selectedOptions.map((option) => (
                    <span key={option.value} className="select-box-chip" data-select-chip>
                        {option.label}
                        <button
                            type="button"
                            className="select-box-chip-remove"
                            aria-label={removeControl.ariaLabelFor(option.label)}
                            data-select-chip-remove
                            onMouseDown={(event) => event.stopPropagation()}
                            onClick={(event) => handleChipRemove(option, event)}
                        >
                            ×
                        </button>
                    </span>
                ))}
                <input
                    ref={inputRef}
                    type="text"
                    className="select-box-input"
                    role="searchbox"
                    aria-autocomplete="list"
                    placeholder={placeholderText}
                    value={state.query}
                    onChange={handleInputChange}
                    onFocus={handleInputFocus}
                    onKeyDown={handleKeyDown}
                    disabled={state.disabled}
                    readOnly={state.readOnly}
                    aria-readonly={state.readOnly || undefined}
                    data-select-input
                />
            </div>
            {clearControl.visible && (
                <button
                    type="button"
                    className="select-box-clear"
                    aria-label={clearControl.ariaLabel}
                    tabIndex={-1}
                    onMouseDown={(event) => event.stopPropagation()}
                    onClick={handleClearAll}
                    data-select-clear
                >
                    {clearControl.label}
                </button>
            )}
        </div>
    );
}

/* ---------------- popover listbox ---------------- */

interface PopoverListboxProps<TExtra extends object> {
    readonly state: SelectBoxSnapshot<TExtra, SelectionValue>;
    readonly controller: SelectBoxController<TExtra, SelectionValue>;
    readonly instanceId: string;
    readonly onAfterCommit: (() => void) | undefined;
}

function PopoverListbox<TExtra extends object>({
    state,
    controller,
    instanceId,
    onAfterCommit,
}: PopoverListboxProps<TExtra>): JSX.Element {
    const isMulti = state.mode === "multi";
    if (state.isEmpty) {
        return (
            <div
                className="select-box-popover"
                role="listbox"
                aria-multiselectable={isMulti ? true : undefined}
                data-select-popover
            >
                <div className="select-box-list" data-select-list>
                    <p className="select-box-empty" data-select-empty>
                        No matches
                    </p>
                </div>
            </div>
        );
    }

    return (
        <div
            className="select-box-popover"
            role="listbox"
            aria-multiselectable={isMulti ? true : undefined}
            data-select-popover
        >
            <VirtualizedOptionList
                state={state}
                controller={controller}
                instanceId={instanceId}
                onAfterCommit={onAfterCommit}
            />
        </div>
    );
}

function VirtualizedOptionList<TExtra extends object>({
    state,
    controller,
    instanceId,
    onAfterCommit,
}: PopoverListboxProps<TExtra>): JSX.Element {
    const isMulti = state.mode === "multi";
    const view = useMemo(() => new SelectBoxSnapshotView<TExtra, SelectionValue>(state), [state]);
    const {
        listRef,
        rowModel,
        virtualItems,
        paddingTop,
        paddingBottom,
        activeRowIndex,
        measureElement,
    } = useSelectBoxVirtualizer<TExtra>({
        groups: state.filteredGroups,
        activeIndex: state.activeIndex,
        viewportHeight: LIST_VIEWPORT_HEIGHT,
        estimateHeader: ESTIMATED_HEADER_HEIGHT,
        estimateOption: ESTIMATED_OPTION_HEIGHT,
    });

    function handleOptionMouseDown(event: MouseEvent<HTMLButtonElement>): void {
        event.preventDefault();
    }

    return (
        <div
            ref={listRef}
            className="select-box-list"
            data-select-list
            style={{ maxHeight: LIST_VIEWPORT_HEIGHT, overflowY: "auto" }}
        >
            <div style={{ paddingTop, paddingBottom }}>
                {virtualItems.map((virtualRow) => {
                    const row = rowModel.getRowAt(virtualRow.index);
                    if (!row) return null;
                    const measureRef = (node: HTMLElement | null): void => measureElement(node);
                    if (row.kind === "header") {
                        return (
                            <div
                                key={`header-${row.groupIndex}`}
                                ref={measureRef}
                                data-index={virtualRow.index}
                                className="select-box-group-label"
                                data-select-group-label
                            >
                                {row.group.label}
                            </div>
                        );
                    }
                    const isActive = virtualRow.index === activeRowIndex;
                    const selected = view.isSelected(row.option.value);
                    const classes = [
                        "select-box-option",
                        isActive ? "select-box-option-active" : null,
                        selected && isMulti ? "select-box-option-selected" : null,
                        row.option.disabled ? "select-box-option-disabled" : null,
                    ]
                        .filter(Boolean)
                        .join(" ");
                    return (
                        <button
                            key={row.option.value}
                            id={optionElementId(instanceId, row.option.value)}
                            ref={measureRef}
                            data-index={virtualRow.index}
                            type="button"
                            role="option"
                            aria-selected={selected}
                            className={classes}
                            disabled={row.option.disabled}
                            onMouseDown={handleOptionMouseDown}
                            onClick={() => {
                                controller.commitOption(row.option);
                                onAfterCommit?.();
                            }}
                            tabIndex={-1}
                            data-select-option
                            data-select-active={isActive ? "" : undefined}
                            data-select-selected={selected ? "" : undefined}
                        >
                            {isMulti ? (
                                <span className="select-box-option-tick" aria-hidden>
                                    {selected ? "✓" : ""}
                                </span>
                            ) : null}
                            <HighlightedLabel
                                label={row.option.label}
                                highlightRanges={state.highlightRanges}
                            />
                        </button>
                    );
                })}
            </div>
        </div>
    );
}

function HighlightedLabel(props: {
    readonly label: string;
    readonly highlightRanges: (label: string) => ReadonlyArray<SearchMatchRange>;
}): JSX.Element {
    const chunks = TextHighlighter.split(props.label, props.highlightRanges(props.label));
    return (
        <>
            {chunks.map((chunk, index) =>
                chunk.matched ? (
                    <mark key={index} className="select-box-option-match">
                        {chunk.text}
                    </mark>
                ) : (
                    <span key={index}>{chunk.text}</span>
                ),
            )}
        </>
    );
}

// packages/vue/src/PopoverSurface.vue
<script setup lang="ts" generic="TExtra extends object = object">
import {
    optionElementId,
    SelectBoxSnapshotView,
    TextHighlighter,
    type HighlightChunk,
    type SelectBoxController,
    type SelectBoxSnapshot,
    type SelectionValue,
    type SelectOption,
} from "@select-box/core";
import FormMirror from "./FormMirror.vue";
import { computed, useId, useTemplateRef } from "vue";

import { useClickOutsideClose } from "./composables/use-click-outside-close.js";
import { useSelectBoxKeyDispatcher } from "./composables/use-select-box-key-dispatcher.js";
import { useSelectBoxVirtualizer } from "./composables/use-select-box-virtualizer.js";

const ESTIMATED_OPTION_HEIGHT = 36;
const ESTIMATED_HEADER_HEIGHT = 28;
const LIST_VIEWPORT_HEIGHT = 240;

const props = defineProps<{
    state: SelectBoxSnapshot<TExtra, SelectionValue>;
    controller: SelectBoxController<TExtra, SelectionValue>;
    placeholder: string | undefined;
    name: string | undefined;
    required: boolean | undefined;
    ariaLabelText: string | undefined;
    ariaLabelledbyRef: string | undefined;
}>();

const instanceId = useId();
// The combobox points at the highlighted row by id; both sides derive it from
// the same snapshot rather than passing an index between components.
const activeDescendant = computed(() =>
    props.state.activeOption === null
        ? undefined
        : optionElementId(instanceId, props.state.activeOption.value),
);

const rootRef = useTemplateRef<HTMLDivElement>("rootEl");

defineExpose({ root: rootRef });
const inputRef = useTemplateRef<HTMLInputElement>("inputEl");

const keyDispatcher = useSelectBoxKeyDispatcher(props.controller);
const isOpen = computed(() => props.state.open);
useClickOutsideClose(rootRef, isOpen, props.controller);

const isMulti = computed(() => props.state.mode === "multi");
const view = computed(
    () => new SelectBoxSnapshotView<TExtra, SelectionValue>(props.state),
);
const inputValue = computed(() => view.value.triggerInputValue);
const hasSelection = computed(() => props.state.selectedOptions.length > 0);
const clearControl = computed(() => view.value.clearControl);
const removeControl = computed(() => view.value.removeControl);
const placeholderText = computed(() => {
    if (isMulti.value) {
        return hasSelection.value ? "" : (props.placeholder ?? "Select…");
    }
    return props.state.open && props.state.selectedOption
        ? props.state.selectedOption.label
        : (props.placeholder ?? "Select…");
});

const filteredGroups = computed(() => props.state.filteredGroups);
const activeIndex = computed(() => props.state.activeIndex);

const {
    rowModel,
    virtualItems,
    paddingTop,
    paddingBottom,
    activeRowIndex,
    measureRow,
} = useSelectBoxVirtualizer<TExtra>({
    groups: filteredGroups,
    activeIndex,
    viewportHeight: LIST_VIEWPORT_HEIGHT,
    estimateHeader: ESTIMATED_HEADER_HEIGHT,
    estimateOption: ESTIMATED_OPTION_HEIGHT,
    listRefName: "listEl",
});

const visibleEntries = computed(() => {
    const model = rowModel.value;
    const active = activeRowIndex.value;
    const currentView = view.value;
    return virtualItems.value.flatMap((virtualRow) => {
        const row = model.getRowAt(virtualRow.index);
        if (row === undefined) return [];
        return [
            {
                virtualRow,
                row,
                isActive: virtualRow.index === active,
                isSelected:
                    row.kind === "option" && currentView.isSelected(row.option.value),
            },
        ];
    });
});

function focusInput(): void {
    inputRef.value?.focus({ preventScroll: true });
}

function handleControlMouseDown(event: MouseEvent): void {
    if (event.target !== inputRef.value) event.preventDefault();
    if (!props.state.open) props.controller.open();
    focusInput();
}

function handleInput(event: Event): void {
    if (!props.state.open) props.controller.open();
    props.controller.setQuery((event.target as HTMLInputElement).value);
}

function handleInputFocus(): void {
    if (!props.state.open) props.controller.open();
}

function handleInputClick(): void {
    if (!props.state.open) props.controller.open();
}

function handleCaretClick(): void {
    if (props.state.open) {
        props.controller.close();
    } else {
        props.controller.open();
        focusInput();
    }
}

function handleKeyDown(event: KeyboardEvent): void {
    if (keyDispatcher.dispatch(event.key) === "handled") {
        event.preventDefault();
    }
}

function handleChipRemove(option: SelectOption<TExtra>, event: MouseEvent): void {
    event.stopPropagation();
    props.controller.commitOption(option);
    focusInput();
}

function handleClearAll(event: MouseEvent): void {
    event.stopPropagation();
    props.controller.clear();
    focusInput();
}

function commitFromList(option: SelectOption<TExtra>): void {
    props.controller.commitOption(option);
    if (isMulti.value) focusInput();
}

function optionClasses(
    isActive: boolean,
    isSelected: boolean,
    disabled: boolean | undefined,
): string {
    return [
        "select-box-option",
        isActive ? "select-box-option-active" : null,
        isSelected && isMulti.value ? "select-box-option-selected" : null,
        disabled ? "select-box-option-disabled" : null,
    ]
        .filter((value): value is string => value !== null)
        .join(" ");
}

function labelChunks(label: string): ReadonlyArray<HighlightChunk> {
    return TextHighlighter.split(label, props.state.highlightRanges(label));
}
</script>

<template>
    <div
        ref="rootEl"
        :class="['select-box', isMulti ? 'select-box-multi' : null].filter(Boolean).join(' ')"
        data-select-root
        :data-select-mode="isMulti ? 'multi' : 'single'"
    >
        <FormMirror :state="state" :controller="controller" :name="name" :required="required" />
        <!-- Multi-mode trigger: chips inside the input, click anywhere opens -->
        <div
            v-if="isMulti"
            class="select-box-trigger"
            data-select-trigger
            role="combobox"
            :aria-label="ariaLabelText"
            :aria-labelledby="ariaLabelledbyRef"
                :aria-activedescendant="activeDescendant"
            aria-haspopup="listbox"
            :aria-expanded="state.open"
            @mousedown="handleControlMouseDown"
        >
            <div class="select-box-tags" data-select-tags>
                <span
                    v-for="option in state.selectedOptions"
                    :key="option.value"
                    class="select-box-chip"
                    data-select-chip
                >
                    {{ option.label }}
                    <button
                        type="button"
                        class="select-box-chip-remove"
                        :aria-label="removeControl.ariaLabelFor(option.label)"
                        data-select-chip-remove
                        @mousedown.stop
                        @click="(event) => handleChipRemove(option, event)"
                    >×</button>
                </span>
                <input
                    ref="inputEl"
                    type="text"
                    class="select-box-input"
                    role="searchbox"
                    aria-autocomplete="list"
                    :placeholder="placeholderText"
                    :value="state.query"
                    :disabled="state.disabled"
                    :readonly="state.readOnly"
                    :aria-readonly="state.readOnly || undefined"
                    data-select-input
                    @input="handleInput"
                    @focus="handleInputFocus"
                    @keydown="handleKeyDown"
                />
            </div>
            <button
                v-if="clearControl.visible"
                type="button"
                class="select-box-clear"
                :aria-label="clearControl.ariaLabel"
                tabindex="-1"
                data-select-clear
                @mousedown.stop
                @click="handleClearAll"
            >{{ clearControl.label }}</button>
        </div>

        <!-- Single-mode trigger: plain input + caret button -->
        <div v-else class="select-box-trigger" data-select-trigger>
            <input
                ref="inputEl"
                type="text"
                class="select-box-input"
                role="combobox"
                :aria-label="ariaLabelText"
                :aria-labelledby="ariaLabelledbyRef"
                :aria-activedescendant="activeDescendant"
                aria-haspopup="listbox"
                aria-autocomplete="list"
                :aria-expanded="state.open"
                :placeholder="placeholderText"
                :value="inputValue"
                :disabled="state.disabled"
                :readonly="state.readOnly"
                :aria-readonly="state.readOnly || undefined"
                data-select-input
                @input="handleInput"
                @focus="handleInputFocus"
                @click="handleInputClick"
                @keydown="handleKeyDown"
            />
            <button
                type="button"
                class="select-box-caret"
                data-select-caret
                tabindex="-1"
                aria-hidden="true"
                @mousedown.prevent
                @click="handleCaretClick"
            >▾</button>
            <button
                v-if="clearControl.visible"
                type="button"
                class="select-box-clear"
                :aria-label="clearControl.ariaLabel"
                tabindex="-1"
                data-select-clear
                @mousedown.stop
                @click="handleClearAll"
            >{{ clearControl.label }}</button>
        </div>

        <div
            v-if="state.open"
            class="select-box-popover"
            role="listbox"
            :aria-multiselectable="isMulti ? true : undefined"
            data-select-popover
        >
            <div
                ref="listEl"
                class="select-box-list"
                data-select-list
                :style="{ maxHeight: `${LIST_VIEWPORT_HEIGHT}px`, overflowY: 'auto' }"
            >
                <p v-if="state.isEmpty" class="select-box-empty" data-select-empty>No matches</p>
                <div
                    v-else
                    :style="{
                        paddingTop: `${paddingTop}px`,
                        paddingBottom: `${paddingBottom}px`,
                    }"
                >
                    <template v-for="entry in visibleEntries" :key="entry.virtualRow.index">
                        <div
                            v-if="entry.row.kind === 'header'"
                            :ref="measureRow"
                            :data-index="entry.virtualRow.index"
                            class="select-box-group-label"
                            data-select-group-label
                        >
                            {{ entry.row.group.label }}
                        </div>
                        <button
                            v-else
                            :ref="measureRow"
                            :data-index="entry.virtualRow.index"
                            type="button"
                            role="option"
                            :aria-selected="entry.isSelected"
                            :class="optionClasses(entry.isActive, entry.isSelected, entry.row.option.disabled)"
                            :disabled="entry.row.option.disabled"
                            tabindex="-1"
                            :id="optionElementId(instanceId, entry.row.option.value)"
                            data-select-option
                            :data-select-active="entry.isActive ? '' : undefined"
                            :data-select-selected="entry.isSelected ? '' : undefined"
                            @mousedown.prevent
                            @click="commitFromList(entry.row.option)"
                        >
                            <span
                                v-if="isMulti"
                                class="select-box-option-tick"
                                aria-hidden="true"
                            >{{ entry.isSelected ? "✓" : "" }}</span>
                            <template
                                v-for="(chunk, chunkIndex) in labelChunks(entry.row.option.label)"
                                :key="chunkIndex"
                            >
                                <mark v-if="chunk.matched" class="select-box-option-match">{{ chunk.text }}</mark>
                                <template v-else>{{ chunk.text }}</template>
                            </template>
                        </button>
                    </template>
                </div>
            </div>
        </div>
    </div>
</template>
