// packages/react/src/SelectBox.tsx
import {
    type OptionFilterStrategy,
    type SelectBoxAddon,
    type SelectBoxController,
    type SelectBoxControllerConfig,
    type SelectionValue,
    type SelectionValueInput,
    type SelectOption,
} from "@select-box/core";
import {
    useEffect,
    useImperativeHandle,
    useRef,
    type CSSProperties,
    type FocusEventHandler,
    type JSX,
    type Ref,
} from "react";

import { useFilterReactivity } from "./hooks/use-filter-reactivity.js";
import { useInteractivityReactivity } from "./hooks/use-interactivity-reactivity.js";
import { useOptionsReactivity } from "./hooks/use-options-reactivity.js";
import { useNotifyChange } from "./hooks/use-notify-change.js";
import { usePropWarnings } from "./hooks/use-prop-warnings.js";
import { useSelectBox } from "./hooks/use-select-box.js";
import { useValueReactivity } from "./hooks/use-value-reactivity.js";
import { InlineSurface } from "./InlineSurface.js";
import { PopoverSurface } from "./PopoverSurface.js";

/** Rendering style. `"popover"` is the default combobox-with-dropdown surface;
 * `"inline"` renders every option as a toggleable chip with no popover, no
 * trigger input, and no search. Selection cardinality (`multi`) is orthogonal
 * — both surfaces work in single and multi modes. Mutable at runtime. */
export type SelectBoxSurface = "popover" | "inline";

/**
 * Imperative handle a `ref` on `<SelectBox>` receives.
 *
 * Escape hatch for behaviour the props do not cover; carries the same two
 * members every wrapper exposes.
 */
export interface SelectBoxHandle<TExtra extends object = object> {
    /** Root element, the same node `data-select-root` marks. */
    readonly root: HTMLDivElement | null;
    /** Core controller driving this instance. */
    readonly controller: SelectBoxController<TExtra, SelectionValue>;
}

interface SelectBoxBaseProps<TExtra extends object> {
    readonly options?: ReadonlyArray<SelectOption<TExtra>> | undefined;
    readonly placeholder?: string | undefined;
    readonly ungroupedLabel?: string | undefined;
    readonly addons?: ReadonlyArray<SelectBoxAddon<TExtra>> | undefined;
    readonly filter?: OptionFilterStrategy<TExtra> | undefined;
    readonly surface?: SelectBoxSurface | undefined;
    /** Refuses every interaction and stays out of the form data, like a disabled input. */
    readonly disabled?: boolean | undefined;
    /** Refuses changes while staying focusable and submitted, like a readonly input. */
    readonly readOnly?: boolean | undefined;
    /** Field name under which the selection is submitted. Omit to stay out of the form. */
    readonly name?: string | undefined;
    /** Blocks submission while nothing is selected, natively. */
    readonly required?: boolean | undefined;
    readonly className?: string | undefined;
    readonly style?: CSSProperties | undefined;
    /**
     * Identifies the whole component; lands on the root element.
     *
     * Not what `<label for>` should point at — a label has to target a
     * labelable control, which is the trigger input. Use `inputId` for that.
     */
    readonly id?: string | undefined;
    /**
     * Id for the trigger input, and therefore what `<label for>` must target.
     *
     * The popover surface has the input; the inline surface has none, and
     * ignores this.
     */
    readonly inputId?: string | undefined;
    /** Fires when focus leaves the trigger input — what form libraries call touched. */
    readonly onBlur?: FocusEventHandler<HTMLInputElement> | undefined;
    /** Fires when the trigger input takes focus. */
    readonly onFocus?: FocusEventHandler<HTMLInputElement> | undefined;
    /** Tab order of the trigger input. */
    readonly tabIndex?: number | undefined;
    /** Receives the imperative handle: the root element and the core controller. */
    readonly ref?: Ref<SelectBoxHandle<TExtra>> | undefined;
    readonly "aria-label"?: string | undefined;
    readonly "aria-labelledby"?: string | undefined;
}

/**
 * Props of `<SelectBox />`, shaped by the mode.
 *
 * `TMultiple` carries whether the box accumulates a selection, so `value`,
 * `defaultValue` and `onChange` take the exact shape that mode uses rather than
 * a union the consumer has to narrow. A literal `multiple` fixes it to `true` or
 * `false` and the three are precise; a flag held in state widens it to `boolean`
 * and they widen with it, which is what makes switching mode at runtime typeable
 * at all.
 */
export interface SelectBoxProps<
    TExtra extends object = object,
    TMultiple extends boolean = false,
> extends SelectBoxBaseProps<TExtra> {
    /** Accumulates a selection instead of replacing it, like `<select multiple>`. */
    readonly multiple?: TMultiple;
    /**
     * Selection owned by the caller, applied even while the control refuses input.
     *
     * Makes the box controlled: a pick the owner does not answer through
     * `onChange` is reverted to what the prop still says, as with `<select value>`.
     */
    readonly value?: TMultiple extends true
        ? ReadonlyArray<string | number>
        : string | number | null;
    /** Initial selection for an uncontrolled box. Ignored once `value` is supplied. */
    readonly defaultValue?: TMultiple extends true
        ? ReadonlyArray<string | number>
        : string | number | null;
    /**
     * Fires whenever the committed selection changes, including `clear()`.
     *
     * Single mode passes the canonical string and the full option; multi passes
     * the list of each.
     */
    readonly onChange?: TMultiple extends true
        ? (
              values: ReadonlyArray<string>,
              options: ReadonlyArray<SelectOption<TExtra>>,
          ) => void
        : (value: string | null, option: SelectOption<TExtra> | null) => void;
}

/** Props of a single-select box. */
export type SelectBoxSingleProps<TExtra extends object = object> = SelectBoxProps<TExtra, false>;

/** Props of a multi-select box. */
export type SelectBoxMultiProps<TExtra extends object = object> = SelectBoxProps<TExtra, true>;

export function SelectBox<TExtra extends object = object, TMultiple extends boolean = false>(
    props: SelectBoxProps<TExtra, TMultiple>,
): JSX.Element {
    const initialMulti = props.multiple === true;
    const defaultValue: SelectionValueInput =
        props.value ?? (initialMulti ? (props.defaultValue ?? []) : (props.defaultValue ?? null));

    const controllerConfig: SelectBoxControllerConfig<TExtra> = {
        mode: initialMulti ? "multi" : "single",
        ...(props.options !== undefined ? { options: props.options } : {}),
        ...(props.addons !== undefined ? { addons: props.addons } : {}),
        ...(props.filter !== undefined ? { filter: props.filter } : {}),
        ...(props.ungroupedLabel !== undefined ? { ungroupedLabel: props.ungroupedLabel } : {}),
        defaultValue,
        disabled: props.disabled === true,
        readOnly: props.readOnly === true,
    };

    const { state, controller } = useSelectBox<TExtra>(
        controllerConfig as Parameters<typeof useSelectBox<TExtra>>[0],
    );

    const wantMulti = props.multiple === true;
    useEffect(() => {
        const currentMulti = controller.mode === "multi";
        if (currentMulti !== wantMulti) {
            controller.setMode(wantMulti ? "multi" : "single");
        }
    }, [controller, wantMulti]);

    usePropWarnings({
        value: props.value,
        defaultValue: props.defaultValue,
        onChange: props.onChange,
        disabled: props.disabled,
        readOnly: props.readOnly,
    });

    // Shared between the two directions of a controlled value: what the owner
    // pushed in, so the notifier does not read it back out as a fresh change.
    const ownerEcho = useRef<string | null>(null);

    // Order matters: the notifier reads the snapshot that just published, and
    // the value sync overwrites the echo with what it is about to push. Announce
    // first, assert second, or every announcement carries the next push's echo.
    useNotifyChange(state, props.onChange, ownerEcho);
    useValueReactivity(controller, props.value, state.value, ownerEcho);
    useFilterReactivity(controller, props.filter);
    useOptionsReactivity(controller, props.options);
    useInteractivityReactivity(controller, props.disabled, props.readOnly);

    const rootRef = useRef<HTMLDivElement>(null);
    // `root` is a getter, not a captured value: switching surfaces mounts a
    // different root element, and a captured node would dangle outside the tree.
    useImperativeHandle(
        props.ref,
        () => ({
            get root(): HTMLDivElement | null {
                return rootRef.current;
            },
            controller,
        }),
        [controller],
    );

    if (props.surface === "inline") {
        return (
            <InlineSurface<TExtra>
                state={state}
                controller={controller}
                rootRef={rootRef}
                name={props.name}
                required={props.required}
                className={props.className}
                style={props.style}
                id={props.id}
                onBlur={props.onBlur}
                onFocus={props.onFocus}
                ariaLabel={props["aria-label"]}
                ariaLabelledby={props["aria-labelledby"]}
            />
        );
    }

    return (
        <PopoverSurface<TExtra>
            state={state}
            controller={controller}
            rootRef={rootRef}
            name={props.name}
            required={props.required}
            placeholder={props.placeholder}
            className={props.className}
            style={props.style}
            id={props.id}
            inputId={props.inputId}
            onBlur={props.onBlur}
            onFocus={props.onFocus}
            tabIndex={props.tabIndex}
            ariaLabel={props["aria-label"]}
            ariaLabelledby={props["aria-labelledby"]}
        />
    );
}

// packages/vue/src/SelectBox.vue
<script setup lang="ts" generic="TExtra extends object = object">
import {
    type OptionFilterStrategy,
    type SelectBoxAddon,
    type SelectBoxController,
    type SelectBoxSnapshot,
    type SelectionValue,
    type SelectOption,
} from "@select-box/core";
import { computed, ref, watch, type ShallowRef } from "vue";

import { useFilterReactivity } from "./composables/use-filter-reactivity.js";
import { useInteractivityReactivity } from "./composables/use-interactivity-reactivity.js";
import { useOptionsReactivity } from "./composables/use-options-reactivity.js";
import { useNotifyChange } from "./composables/use-notify-change.js";
import { useValueReactivity, type OwnerEcho } from "./composables/use-value-reactivity.js";
import { useSelectBox } from "./composables/use-select-box.js";
import InlineSurface from "./InlineSurface.vue";
import PopoverSurface from "./PopoverSurface.vue";

/** Rendering style. `"popover"` is the default combobox-with-dropdown surface;
 * `"inline"` renders every option as a toggleable chip with no popover, no
 * trigger input, and no search. Orthogonal to `multi` — both surfaces work in
 * single and multi modes. */
export type SelectBoxSurface = "popover" | "inline";

export interface SelectBoxProps<TExtra extends object = object> {
    options?: ReadonlyArray<SelectOption<TExtra>>;
    /**
     * Selection owned by the caller, applied even while the control refuses input.
     *
     * Makes the box controlled: a pick the owner does not answer through the
     * `change` event is reverted to what the prop still says.
     */
    value?: string | number | null | ReadonlyArray<string | number>;
    /** Initial selection for an uncontrolled box. Ignored once `value` is supplied. */
    defaultValue?: string | number | null | ReadonlyArray<string | number>;
    placeholder?: string;
    ungroupedLabel?: string;
    addons?: ReadonlyArray<SelectBoxAddon<TExtra>>;
    filter?: OptionFilterStrategy<TExtra>;
    /** When `true`, switches to multi-select (chips inside the input, popover stays open on commit). */
    multi?: boolean;
    /** Surface style. Defaults to `"popover"`. */
    surface?: SelectBoxSurface;
    /** Refuses every interaction and stays out of the form data, like a disabled input. */
    disabled?: boolean;
    /** Refuses changes while staying focusable and submitted, like a readonly input. */
    readOnly?: boolean;
    /** Field name under which the selection is submitted. Omit to stay out of the form. */
    name?: string;
    /** Blocks submission while nothing is selected, natively. */
    required?: boolean;
    /**
     * Accessible name for the combobox.
     *
     * An explicit prop rather than attribute fallthrough, because a bare
     * `aria-label` would land on the root and the role lives on a child.
     */
    ariaLabel?: string;
    ariaLabelledby?: string;
}

const props = withDefaults(defineProps<SelectBoxProps<TExtra>>(), {
    defaultValue: null,
    multi: false,
    surface: "popover",
    disabled: false,
    readOnly: false,
});
const emit = defineEmits<{
    /** Single-mode change. Fires only when `multi` is `false`. */
    (event: "change", value: string | null, option: SelectOption<TExtra> | null): void;
    /** Multi-mode change. Fires only when `multi` is `true`. */
    (
        event: "change-multi",
        values: ReadonlyArray<string>,
        options: ReadonlyArray<SelectOption<TExtra>>,
    ): void;
}>();

function commonConfig() {
    return {
        ...(props.options !== undefined ? { options: props.options } : {}),
        ...(props.addons !== undefined ? { addons: props.addons } : {}),
        ...(props.filter !== undefined ? { filter: props.filter } : {}),
        ...(props.ungroupedLabel !== undefined ? { ungroupedLabel: props.ungroupedLabel } : {}),
        disabled: props.disabled,
        readOnly: props.readOnly,
    };
}

// Branch at the call site so each useSelectBox call hits a specific overload
// at construction; thereafter the controller's mode can flip at runtime via
// setMode without recreating the controller (selection preserved across the
// flip via the driver's coerce step).
const useResult = props.multi
    ? useSelectBox<TExtra>({
        mode: "multi",
        ...commonConfig(),
        initialValue: (props.value ?? (Array.isArray(props.defaultValue)
            ? (props.defaultValue as ReadonlyArray<string | number>)
            : [])) as ReadonlyArray<string | number>,
    })
    : useSelectBox<TExtra>({
        ...commonConfig(),
        initialValue: (props.value ?? (Array.isArray(props.defaultValue)
            ? null
            : props.defaultValue)) as string | number | null,
    });

const state = useResult.state as ShallowRef<SelectBoxSnapshot<TExtra, SelectionValue>>;
const controller = useResult.controller as SelectBoxController<TExtra, SelectionValue>;

watch(
    () => props.multi,
    (multi) => {
        controller.setMode(multi ? "multi" : "single");
    },
);

useFilterReactivity(controller, computed(() => props.filter));
useOptionsReactivity(controller, computed(() => props.options));
useInteractivityReactivity(
    controller,
    computed(() => props.disabled),
    computed(() => props.readOnly),
);
// Shared between the two directions of a controlled value: what the owner
// pushed in, so the notifier does not read it back out as a fresh change.
const ownerEcho: OwnerEcho = { current: null };

// Order matters. Watchers run in creation order, so the announcement has to be
// registered before the push that stamps the next echo.
useNotifyChange(
    state,
    {
        single: (value, option) => emit("change", value, option),
        multi: (values, options) => emit("change-multi", values, options),
    },
    ownerEcho,
);
useValueReactivity(
    controller,
    computed(() => props.value),
    state,
    ownerEcho,
);

const isInline = computed(() => props.surface === "inline");

const surfaceInstance = ref<{ root: HTMLDivElement | null } | null>(null);

/**
 * Imperative surface reachable through a template ref: the root element and the
 * core controller, the same two members every wrapper exposes.
 */
defineExpose({
    get root(): HTMLDivElement | null {
        return surfaceInstance.value?.root ?? null;
    },
    controller,
});
</script>

<template>
    <InlineSurface
        v-if="isInline"
        ref="surfaceInstance"
        :state="state"
        :controller="controller"
        :name="name"
        :required="required"
        :aria-label-text="ariaLabel"
        :aria-labelledby-ref="ariaLabelledby"
    />
    <PopoverSurface
        v-else
        ref="surfaceInstance"
        :state="state"
        :controller="controller"
        :placeholder="placeholder"
        :name="name"
        :required="required"
        :aria-label-text="ariaLabel"
        :aria-labelledby-ref="ariaLabelledby"
    />
</template>
